### ISSUE TITLE
Seeding Gemstones

### ISSUE THREAD

**Issue by IcyN30N** [ModifiedChocolateUnicorn/PaveJadeBaguette#1]
Add each brand gemstones to the seeds file

- [x] Anatometal
- [x] BVLA
- [x] IS
- [x] Neometal

**Comment by ModifiedChocolateUnicorn** [comment]
BVLA stones : 
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by ModifiedChocolateUnicorn** [comment]
Industrial Strength stones : :gem: 
[ ] Brilliant
[ ] Cabochon
[ ] Princess

**Comment by ModifiedChocolateUnicorn** [comment]
Neometal stones : gem
- [ ] Brilliant
- [ ] Cabochon
- [ ] Princess (white cz only !)
